modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"
[[mods]]
modId="goldenexpansion"
version="1.0"
displayName="The Golden Expansion"
logoFile="goldenexpansionicon.png"
credits=""
authors=""

description='''

'''

[[dependencies.goldenexpansion]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.goldenexpansion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
